<a href="https://colab.research.google.com/github/nikspatil0120/23102A0057_RProgramming/blob/main/23102A0057_R_Week10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nikhil Patil

BE CMPN A 23102A0057

## String Manipulation

### Initializing a String Variable

In [1]:
y="Number of participants: 25"

In [ ]:
# Assign a string value to variable 'y'
y='Number of participants: 25'

### Using `sub()` for First Occurrence Replacement

In [2]:
sub("25","30",y)

[1] "Number of participants: 30"

In [ ]:
# Use sub() to replace the first occurrence of '25' with '30' in string 'y'
sub('25','30',y)

### Re-initializing for Global Replacement Demonstration

In [4]:
y="Mr. Singh is the smart one. Mr. Singh is funny, too."
y

[1] "Mr. Singh is the smart one. Mr. Singh is funny, too."

In [ ]:
# Assign a new string to 'y' and display it
y='Mr. Singh is the smart one. Mr. Singh is funny, too.'
y

In [6]:
sub("Mr. Singh","Professor Jha",y)

[1] "Professor Jha is the smart one. Mr. Singh is funny, too."

In [ ]:
# Use sub() to replace the first occurrence of 'Mr. Singh' with 'Professor Jha' in string 'y'
sub('Mr. Singh','Professor Jha',y)

In [7]:
y="Mr. Singh is the smart one. Mr. Singh is funny, too."
y

[1] "Mr. Singh is the smart one. Mr. Singh is funny, too."

In [ ]:
# Re-assign the original string to 'y' and display it (resetting for gsub example)
y='Mr. Singh is the smart one. Mr. Singh is funny, too.'
y

### Using `gsub()` for Global Replacement

In [8]:
gsub("Mr. Singh","Professor Jha",y)

[1] "Professor Jha is the smart one. Professor Jha is funny, too."

In [ ]:
# Use gsub() to replace all occurrences of 'Mr. Singh' with 'Professor Jha' in string 'y'
gsub('Mr. Singh','Professor Jha',y)

### Creating a Character Vector for Pattern Matching

In [9]:
str = c("R Course","exercises","include example of R language")

In [ ]:
# Create a character vector 'str'
str = c('R Course','exercises','include example of R language')

### `grep()` Usage: Returning Matching Values

## Pattern Matching with `grep()` and `grepl()`

In [10]:
grep("ex",str,value=T)

[1] "exercises"                     "include example of R language"

In [ ]:
# Use grep() to find elements containing 'ex' and return the matching values (`value=T`)
grep('ex',str,value=T)

### `grep()` with `value=FALSE`: Returning Indices

In [11]:
str=c("R Course","exercises","inlcude examples of R language")

In [ ]:
# Re-assign 'str' with a slightly different third element
str=c('R Course','exercises','inlcude examples of R language')

In [12]:
grep("ex",str,value=F)

[1] 2 3

In [ ]:
# Use grep() to find elements containing 'ex' and return their indices (`value=F`)
grep('ex',str,value=F)

### Demonstrating Case Sensitivity in `grep()` (Value Return)

In [13]:
str=c("R Course","exercises","inlcude examples of R language","in R software")

In [ ]:
# Re-assign 'str' with an additional element
str=c('R Course','exercises','inlcude examples of R language','in R software')

In [14]:
grep("R",str,ignore.case=F,value=T)

[1] "R Course"                       "inlcude examples of R language"
[3] "in R software"

In [ ]:
# Use grep() to find elements containing 'R' (case-sensitive) and return values
grep('R',str,ignore.case=F,value=T)

### Demonstrating Case Sensitivity in `grep()` (Index Return)

In [15]:
grep("R",str,ignore.case=T,value=F)

[1] 1 2 3 4

In [ ]:
# Use grep() to find elements containing 'R' (case-insensitive) and return indices
grep('R',str,ignore.case=T,value=F)

In [16]:
grep("R",str,ignore.case=F,value=F)

[1] 1 3 4

In [ ]:
# Use grep() to find elements containing 'R' (case-sensitive) and return indices
grep('R',str,ignore.case=F,value=F)

### Combining Strings and `grep()` for Specific Patterns

In [18]:
x="R Course 24.07.2022"
y="Number of participants: 50"

In [ ]:
# Assign two separate strings to 'x' and 'y'
x='R Course 24.07.2022'
y='Number of participants: 50'

In [19]:
c(x,y)

[1] "R Course 24.07.2022"        "Number of participants: 50"

In [ ]:
# Combine 'x' and 'y' into a character vector
c(x,y)

In [20]:
grep("Num",c(x,y))

[1] 2

In [ ]:
# Use grep() to find elements containing 'Num' in the combined vector and return indices
grep('Num',c(x,y))

### Using `grepl()` for Logical Vector Output

In [21]:
str=c("R Course","exercises","inlcude examples of R language")
str

[1] "R Course"                       "exercises"
[3] "inlcude examples of R language"

In [ ]:
# Re-assign 'str' and display it
str=c('R Course','exercises','inlcude examples of R language')
str

In [23]:
grepl("R",str)

[1]  TRUE FALSE  TRUE

In [ ]:
# Use grepl() to check for 'R' (case-sensitive) in each element of 'str', returning logical values
grepl('R',str)

### More `grepl()` Examples

In [24]:
grepl("ex",str)

[1] FALSE  TRUE  TRUE

In [ ]:
# Use grepl() to check for 'ex' (case-sensitive) in each element of 'str', returning logical values
grepl('ex',str)

### Loading and Viewing the `painters` Dataset

In [26]:
library(MASS)
painters

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A
F. Zucarro      10          13       8      8         B
Fr. Salviata    13          15       8      8         B
Parmigiano      10          15       6      6         B
Primaticcio     15          14       7     10         B
T. Zucarro      13          14      10      9         B
Volterra        12          15       5      8         B
Barocci         14          15       6     10         C
Cortona         16          14      12      6         C
Josepin         10          10       6      2         C
L. Jordaens     13          12       9      6         C
Testa           11          15       0      6         C
Vanius          15          15      12     13         C
Bassano          6           8      17      0         D
Bellini          4           6      14      0         D
Giorgione        8           9      18      4         D
Murillo          6           8      15      4         D
Palma Giovane   12           9      14      6         D
Palma Vecchio    5           6      16      0         D
Pordenone        8          14      17      5         D
Tintoretto      15          14      16      4         D
Titian          12          15      18      6         D
Veronese        15          10      16      3         D
Albani          14          14      10      6         E
Caravaggio       6           6      16      0         E
Corregio        13          13      15     12         E
Domenichino     15          17       9     17         E
Guercino        18          10      10      4         E
Lanfranco       14          13      10      5         E
The Carraci     15          17      13     13         E
Durer            8          10      10      8         F
Holbein          9          10      16     13         F
Pourbus          4          15       6      6         F
Van Leyden       8           6       6      4         F
Diepenbeck      11          10      14      6         G
J. Jordaens     10           8      16      6         G
Otho Venius     13          14      10     10         G
Rembrandt       15           6      17     12         G
Rubens          18          13      17     17         G
Teniers         15          12      13      6         G
Van Dyck        15          10      17     13         G
Bourdon         10           8       8      4         H
Le Brun         16          16       8     16         H
Le Suer         15          15       4     15         H
Poussin         15          17       6     15         H

In [ ]:
# Load the MASS library and display the 'painters' dataset
library(MASS)
painters

## Working with Dataframes (MASS Painters Dataset)

In [28]:
rownames(painters)

 [1] "Da Udine"        "Da Vinci"        "Del Piombo"      "Del Sarto"
 [5] "Fr. Penni"       "Guilio Romano"   "Michelangelo"    "Perino del Vaga"
 [9] "Perugino"        "Raphael"         "F. Zucarro"      "Fr. Salviata"
[13] "Parmigiano"      "Primaticcio"     "T. Zucarro"      "Volterra"
[17] "Barocci"         "Cortona"         "Josepin"         "L. Jordaens"
[21] "Testa"           "Vanius"          "Bassano"         "Bellini"
[25] "Giorgione"       "Murillo"         "Palma Giovane"   "Palma Vecchio"
[29] "Pordenone"       "Tintoretto"      "Titian"          "Veronese"
[33] "Albani"          "Caravaggio"      "Corregio"        "Domenichino"
[37] "Guercino"        "Lanfranco"       "The Carraci"     "Durer"
[41] "Holbein"         "Pourbus"         "Van Leyden"      "Diepenbeck"
[45] "J. Jordaens"     "Otho Venius"     "Rembrandt"       "Rubens"
[49] "Teniers"         "Van Dyck"        "Bourdon"         "Le Brun"
[53] "Le Suer"         "Poussin"

In [ ]:
# Get the row names of the 'painters' dataframe
rownames(painters)

### Checking Data Types of Specific Columns

In [30]:
is.numeric(painters$School)

[1] FALSE

In [ ]:
# Check if the 'School' column is numeric
is.numeric(painters$School)

In [31]:
is.numeric(painters$Drawing)

[1] TRUE

In [ ]:
# Check if the 'Drawing' column is numeric
is.numeric(painters$Drawing)

In [32]:
is.factor(painters$School)

[1] TRUE

In [ ]:
# Check if the 'School' column is a factor
is.factor(painters$School)

In [33]:
is.factor(painters$Drawing)

[1] FALSE

In [ ]:
# Check if the 'Drawing' column is a factor
is.factor(painters$Drawing)

### Retrieving Column Names

In [34]:
colnames(painters)

[1] "Composition" "Drawing"     "Colour"      "Expression"  "School"

In [ ]:
# Get the column names of the 'painters' dataframe
colnames(painters)

### Summarizing the Entire Dataframe

In [35]:
summary(painters)

  Composition       Drawing          Colour        Expression         School
 Min.   : 0.00   Min.   : 6.00   Min.   : 0.00   Min.   : 0.000   A      :10
 1st Qu.: 8.25   1st Qu.:10.00   1st Qu.: 7.25   1st Qu.: 4.000   D      :10
 Median :12.50   Median :13.50   Median :10.00   Median : 6.000   E      : 7
 Mean   :11.56   Mean   :12.46   Mean   :10.94   Mean   : 7.667   G      : 7
 3rd Qu.:15.00   3rd Qu.:15.00   3rd Qu.:16.00   3rd Qu.:11.500   B      : 6
 Max.   :18.00   Max.   :18.00   Max.   :18.00   Max.   :18.000   C      : 6
                                                                  (Other): 8

In [ ]:
# Display a summary of the 'painters' dataframe
summary(painters)

### Summarizing Specific Columns

In [37]:
library(MASS)
painters

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A
F. Zucarro      10          13       8      8         B
Fr. Salviata    13          15       8      8         B
Parmigiano      10          15       6      6         B
Primaticcio     15          14       7     10         B
T. Zucarro      13          14      10      9         B
Volterra        12          15       5      8         B
Barocci         14          15       6     10         C
Cortona         16          14      12      6         C
Josepin         10          10       6      2         C
L. Jordaens     13          12       9      6         C
Testa           11          15       0      6         C
Vanius          15          15      12     13         C
Bassano          6           8      17      0         D
Bellini          4           6      14      0         D
Giorgione        8           9      18      4         D
Murillo          6           8      15      4         D
Palma Giovane   12           9      14      6         D
Palma Vecchio    5           6      16      0         D
Pordenone        8          14      17      5         D
Tintoretto      15          14      16      4         D
Titian          12          15      18      6         D
Veronese        15          10      16      3         D
Albani          14          14      10      6         E
Caravaggio       6           6      16      0         E
Corregio        13          13      15     12         E
Domenichino     15          17       9     17         E
Guercino        18          10      10      4         E
Lanfranco       14          13      10      5         E
The Carraci     15          17      13     13         E
Durer            8          10      10      8         F
Holbein          9          10      16     13         F
Pourbus          4          15       6      6         F
Van Leyden       8           6       6      4         F
Diepenbeck      11          10      14      6         G
J. Jordaens     10           8      16      6         G
Otho Venius     13          14      10     10         G
Rembrandt       15           6      17     12         G
Rubens          18          13      17     17         G
Teniers         15          12      13      6         G
Van Dyck        15          10      17     13         G
Bourdon         10           8       8      4         H
Le Brun         16          16       8     16         H
Le Suer         15          15       4     15         H
Poussin         15          17       6     15         H

In [ ]:
# Re-load the MASS library and display the 'painters' dataset (demonstration)
library(MASS)
painters

### Inspecting Row Names

In [38]:
summary(painters$School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

In [ ]:
# Display a summary of the 'School' column specifically
summary(painters$School)

### Attaching Dataframe for Direct Column Access

In [40]:
attach(painters)
summary(School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

In [ ]:
# Attach the 'painters' dataframe to the search path and summarize 'School' directly
attach(painters)
summary(School)

### Summarizing Attached Columns

In [41]:
summary(Composition)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

In [ ]:
# Summarize the 'Composition' column (accessible directly after attach())
summary(Composition)

### Subsetting by Row Condition with `subset()`

In [45]:
subset(painters,School=='F')

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

In [ ]:
# Subset the 'painters' dataframe to include only rows where 'School' is 'F'
subset(painters,School=='F')

### Subsetting with Bracket Notation

## Subsetting Dataframes

In [46]:
painters[painters[["School"]]=="F", ]

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

In [ ]:
# Achieve the same subsetting using bracket notation
painters[painters[['School']]=='F', ]

### Subsetting by Numeric Condition

In [47]:
subset(painters,Composition<=6)

              Composition Drawing Colour Expression School
Fr. Penni     0           15       8     0          A
Perugino      4           12      10     4          A
Bassano       6            8      17     0          D
Bellini       4            6      14     0          D
Murillo       6            8      15     4          D
Palma Vecchio 5            6      16     0          D
Caravaggio    6            6      16     0          E
Pourbus       4           15       6     6          F

In [ ]:
# Subset the 'painters' dataframe to include only rows where 'Composition' is less than or equal to 6
subset(painters,Composition<=6)

### Subsetting Rows and Selecting Columns

In [48]:
subset(painters,School=="F",select=c(-3,-5))

           Composition Drawing Expression
Durer      8           10       8
Holbein    9           10      13
Pourbus    4           15       6
Van Leyden 8            6       4

In [ ]:
# Subset by 'School' and select all columns except the 3rd and 5th
subset(painters,School=='F',select=c(-3,-5))

### Splitting a Dataframe by a Factor Column

In [49]:
splitted=split(painters,painters$School)
splitted

$A
                Composition Drawing Colour Expression School
Da Udine                 10       8     16          3      A
Da Vinci                 15      16      4         14      A
Del Piombo                8      13     16          7      A
Del Sarto                12      16      9          8      A
Fr. Penni                 0      15      8          0      A
Guilio Romano            15      16      4         14      A
Michelangelo              8      17      4          8      A
Perino del Vaga          15      16      7          6      A
Perugino                  4      12     10          4      A
Raphael                  17      18     12         18      A

$B
             Composition Drawing Colour Expression School
F. Zucarro            10      13      8          8      B
Fr. Salviata          13      15      8          8      B
Parmigiano            10      15      6          6      B
Primaticcio           15      14      7         10      B
T. Zucarro            13      14     10          9      B
Volterra              12      15      5          8      B

$C
            Composition Drawing Colour Expression School
Barocci              14      15      6         10      C
Cortona              16      14     12          6      C
Josepin              10      10      6          2      C
L. Jordaens          13      12      9          6      C
Testa                11      15      0          6      C
Vanius               15      15     12         13      C

$D
              Composition Drawing Colour Expression School
Bassano                 6       8     17          0      D
Bellini                 4       6     14          0      D
Giorgione               8       9     18          4      D
Murillo                 6       8     15          4      D
Palma Giovane          12       9     14          6      D
Palma Vecchio           5       6     16          0      D
Pordenone               8      14     17          5      D
Tintoretto             15      14     16          4      D
Titian                 12      15     18          6      D
Veronese               15      10     16          3      D

$E
            Composition Drawing Colour Expression School
Albani               14      14     10          6      E
Caravaggio            6       6     16          0      E
Corregio             13      13     15         12      E
Domenichino          15      17      9         17      E
Guercino             18      10     10          4      E
Lanfranco            14      13     10          5      E
The Carraci          15      17     13         13      E

$F
           Composition Drawing Colour Expression School
Durer                8      10     10          8      F
Holbein              9      10     16         13      F
Pourbus              4      15      6          6      F
Van Leyden           8       6      6          4      F

$G
            Composition Drawing Colour Expression School
Diepenbeck           11      10     14          6      G
J. Jordaens          10       8     16          6      G
Otho Venius          13      14     10         10      G
Rembrandt            15       6     17         12      G
Rubens               18      13     17         17      G
Teniers              15      12     13          6      G
Van Dyck             15      10     17         13      G

$H
        Composition Drawing Colour Expression School
Bourdon          10       8      8          4      H
Le Brun          16      16      8         16      H
Le Suer          15      15      4         15      H
Poussin          15      17      6         15      H

In [ ]:
# Split the 'painters' dataframe by the 'School' column and store the result in 'splitted'
splitted=split(painters,painters$School)
splitted

### Checking Type of Split Components

## Splitting Dataframes

In [51]:
is.data.frame(splitted$A)

[1] TRUE

In [ ]:
# Check if the component 'A' of the split object is a data frame
is.data.frame(splitted$A)

### Creating Dataframes for Combination Examples

In [54]:
df1=data.frame(state=c("UP","MP","AP","JK"),popnsize=c(1000,2000,3000,4000))
df2=data.frame(state=c("UP","MP","AP","JK"),samplesize=c(100,200,300,400),surveycompleted=c("Yes","No","Yes","No"))

In [ ]:
# Create two data frames, df1 and df2, for demonstration of combining operations
df1=data.frame(state=c('UP','MP','AP','JK'),popnsize=c(1000,2000,3000,4000))
df2=data.frame(state=c('UP','MP','AP','JK'),samplesize=c(100,200,300,400),surveycompleted=c('Yes','No','Yes','No'))

### Displaying Dataframes

## Combining Dataframes (`cbind`, `merge`, `rbind`)

In [55]:
df1

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

In [ ]:
# Display data frame df1
df1

In [56]:
df2

  state samplesize surveycompleted
1 UP    100        Yes
2 MP    200        No
3 AP    300        Yes
4 JK    400        No

In [ ]:
# Display data frame df2
df2

### Column-wise Combination with `cbind()`

In [57]:
cbind(df1,df2)

  state popnsize state samplesize surveycompleted
1 UP    1000     UP    100        Yes
2 MP    2000     MP    200        No
3 AP    3000     AP    300        Yes
4 JK    4000     JK    400        No

In [ ]:
# Combine df1 and df2 by column using cbind()
cbind(df1,df2)

### Merging Dataframes by a Common Column

In [58]:
merge(df1,df2,by="state")

  state popnsize samplesize surveycompleted
1 AP    3000     300        Yes
2 JK    4000     400        No
3 MP    2000     200        No
4 UP    1000     100        Yes

In [ ]:
# Merge df1 and df2 by the common 'state' column using merge()
merge(df1,df2,by='state')

### Creating New Dataframes for Row-wise Combination

In [60]:
df11=data.frame(state=c("UP","MP","AP","JK"),popnsize=c(1000,2000,3000,4000))
df22=data.frame(state=c("Bihar","Delhi","Punjab"),popnsize=c(100,200,300))

In [ ]:
# Create two new data frames, df11 and df22, with different states for rbind demonstration
df11=data.frame(state=c('UP','MP','AP','JK'),popnsize=c(1000,2000,3000,4000))
df22=data.frame(state=c('Bihar','Delhi','Punjab'),popnsize=c(100,200,300))

### Displaying New Dataframes

In [61]:
df11

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

In [ ]:
# Display data frame df11
df11

In [62]:
df22

  state  popnsize
1 Bihar  100
2 Delhi  200
3 Punjab 300

In [ ]:
# Display data frame df22
df22

### Row-wise Combination with `rbind()`

In [63]:
rbind(df11,df22)

  state  popnsize
1 UP     1000
2 MP     2000
3 AP     3000
4 JK     4000
5 Bihar   100
6 Delhi   200
7 Punjab  300

In [ ]:
# Combine df11 and df22 by row using rbind()
rbind(df11,df22)