<a href="https://colab.research.google.com/github/nikspatil0120/23102A0057_RProgramming/blob/main/23102A0057_R_programming_week_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nikhil Patil

BE CMPN A 23102A0057

In [1]:
# Check R version
R.version.string

# Basic test
print("R is working!")

[1] "R version 4.6.1 (2026-06-24)"

[1] "R is working!"

In [29]:
print("The zero occurs at 2*pi radians.")

[1] "The zero occurs at 2*pi radians."

This cell attempts to print a string and a calculated value (`2*pi`) directly within a single `print` function call, which can lead to an error in R if not correctly formatted. It demonstrates a common mistake when trying to combine different types of arguments with `print.default`.

In [30]:
# This will give an error
print("The zero occurs at", 2*pi, "radians.")

ERROR: Error in print.default("The zero occurs at", 2 * pi, "radians."): invalid 'quote' argument

This code demonstrates how to correctly print multiple values by using separate `print` statements for each part, or by combining them as strings. It effectively prints the same message as the intended (but erroneous) code in the previous cell.

In [31]:
print("The zero occurs at")
print(2*pi)
print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

This cell uses the `cat` function, which concatenates and prints its arguments, separating them with spaces by default. It's often preferred for constructing output strings in R.

In [32]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

This code retrieves the current date and time using the `date()` function and then prints it using `cat`, along with a descriptive label.

In [33]:
d = date()

cat("Today's date is:", d, "\n")

Today's date is: Thu Sep 24 05:19:35 2026

This cell creates a numeric vector `x` from 1 to 10 and then uses `cat` to print its elements, demonstrating how to use the `sep` argument to specify a custom separator between elements.

In [34]:
x = 1:10

x

cat(x, sep = " ++ ")
cat("\n")

cat(x, sep = " / ")
cat("\n")

 [1]  1  2  3  4  5  6  7  8  9 10

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

This code defines a variable `x` and then uses `cat` to print a descriptive string along with the value of `x` and its square, demonstrating string interpolation.

In [35]:
x = 7

cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

This code calculates the square root of `x` and formats the output to a specified number of digits using `format` and `sqrt` functions, then prints it using `cat`.

In [36]:
x = 7

cat(
  "The square root of",
  x,
  "is approximately",
  format(sqrt(x), digits = 3),
  "\n"
)

The square root of 7 is approximately 2.65

This cell defines a vector `evenno` and then uses `cat` to print a descriptive string followed by the elements of the vector.

In [37]:
evenno = c(2, 4, 6, 8, 10)

evenno

cat("The first few even numbers are:", evenno, "...\n")

[1]  2  4  6  8 10

The first few even numbers are: 2 4 6 8 10 ...

This code demonstrates the `cat` function with `fill` and `labels` arguments. `fill=2` specifies to fill output lines to 2 characters (though for this input, it might not be immediately apparent), and `labels` provides labels for each element.

In [38]:
x = 1:10

cat(
  x,
  fill = 2,
  labels = paste("(", letters[1:10], "):")
)

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

This cell uses the `paste` function to concatenate numbers into strings (default separator is space) and `as.character` to explicitly convert numbers to character strings.

In [39]:
paste(1:12)

as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

This cell is a duplicate of the previous one, showing the use of `paste` and `as.character` to convert numeric sequences to character vectors.

In [40]:
paste(1:12)

as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

This code demonstrates the basic usage of the `paste` function to concatenate multiple character strings with a default space separator.

In [41]:
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

This cell shows how to use the `sep` argument in the `paste` function to specify a custom separator (e.g., `*` or `===`) when concatenating strings.

In [42]:
paste(
  "Everybody",
  "loves",
  "R Programming.",
  sep = "*"
)

paste(
  "Everybody",
  "loves",
  "R Programming.",
  sep = "==="
)

[1] "Everybody*loves*R Programming."

[1] "Everybody===loves===R Programming."

This code defines a character vector `names` and then uses `paste` to append a common phrase to each name in the vector, demonstrating vectorization in `paste`.

In [43]:
names = c(
  "Prof. Singh",
  "Mr. Venkat",
  "Dr. Jha"
)

names

paste(names, "is", "a good", "person.")

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

This cell uses the `paste` function with the `collapse` argument. When `collapse` is used, the elements of the resulting vector are collapsed into a single string using the specified separator (`, and ` in this case).

In [44]:
names = c(
  "Prof. Singh",
  "Mr. Venkat",
  "Dr. Jha"
)

paste(
  names,
  "is",
  "a good",
  "person.",
  collapse = ", and "
)

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

This code demonstrates concatenating mixed types (numeric and character) with `paste`, using `#` as the separator between arguments.

In [45]:
paste(
  1,
  " is first",
  2,
  " is second",
  3,
  " is third",
  sep = "#"
)

[1] "1# is first#2# is second#3# is third"

This cell uses `paste` to create a character vector where each element combines 'Ex' with a number from 1 to 5, separated by '_'. It then accesses individual elements of this resulting vector.

In [46]:
x = paste("Ex", 1:5, sep = "_")

x

x[1]
x[2]
x[3]
x[5]

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1"

[1] "Ex_2"

[1] "Ex_3"

[1] "Ex_5"

This code uses `paste` with the `collapse` argument to combine all elements of the created character vector into a single string, with no separator between the collapsed elements (due to `collapse = ""`).

In [47]:
x = paste(
  "Ex",
  1:5,
  sep = "_",
  collapse = ""
)

x

x[1]

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

This cell explicitly shows the difference between `paste` without `collapse` (resulting in a vector of strings) and `paste` with `collapse` (resulting in a single concatenated string).

In [48]:
# Without collapse
x1 = paste("Ex", 1:5, sep = "_")

x1


# With collapse
x2 = paste(
  "Ex",
  1:5,
  sep = "_",
  collapse = ""
)

x2

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

This code compares `paste0` and `paste` when used with a single numeric vector. `paste0` is equivalent to `paste(..., sep = "")` and concatenates without a separator by default.

In [49]:
paste0(1:10)

paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

This cell uses `paste0` to combine numbers (1-10) with appropriate suffixes ('st', 'nd', 'rd', 'th') to create ordinal number strings.

In [6]:
paste0(
  1:10,
  c("st", "nd", "rd", rep("th", 7))
)

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

This cell further illustrates the difference between `paste` (which uses a space as default separator) and `paste0` (which uses no separator by default) when combining numbers with suffixes.

In [7]:
paste(
  1:10,
  c("st", "nd", "rd", rep("th", 7))
)

paste0(
  1:10,
  c("st", "nd", "rd", rep("th", 7))
)

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

This code demonstrates the `strsplit` function, which splits a character string into substrings based on a specified delimiter. Here, it splits by `!`.

In [8]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

x

strsplit(x, split = "!")

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

This cell shows `strsplit` with a multi-character delimiter, `&!`, to split the string into parts.

In [9]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

x

strsplit(x, split = "&!")

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

This code uses `strsplit` with another multi-character delimiter (`!&`) and stores the result in a variable `y`. The result is a list.

In [10]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

y = strsplit(x, split = "!&")

y

[[1]]
[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

This cell demonstrates how to access individual elements of the list returned by `strsplit`. Since `strsplit` returns a list where each element is a vector of splits for a corresponding input string, `y[[1]]` accesses the vector for the first (and only) input string, and then `[1]`, `[2]`, etc., access its parts.

In [11]:
y[[1]][1]

y[[1]][2]

y[[1]][3]

[1] "The&!syntax&!of&!paste&!is"

[1] "available! &inthe online-help"

[1] NA

This cell defines a character vector `dates` containing several date strings in 'YYYY-MM-DD' format.

In [12]:
dates = c(
  "2020-07-24",
  "2021-08-25",
  "2022-09-26",
  "2023-10-27"
)

dates

[1] "2020-07-24" "2021-08-25" "2022-09-26" "2023-10-27"

This code applies `strsplit` to the `dates` vector, splitting each date string by the hyphen (`-`), resulting in a list where each element is a vector of year, month, and day.

In [13]:
datesplt = strsplit(dates, "-")

datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

This cell converts the list of split date strings (`datesplt`) into a matrix. `unlist` flattens the list into a single vector, and `matrix` reshapes it into a 4x3 matrix with `byrow=TRUE`.

In [14]:
datemat = matrix(
  unlist(datesplt),
  nrow = 4,
  ncol = 3,
  byrow = TRUE
)

datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

This code is similar to the previous one, but it converts the unlisted date components to numeric values using `as.numeric` before creating the matrix, resulting in a matrix of numbers.

In [15]:
datematrix = matrix(
  as.numeric(unlist(datesplt)),
  nrow = 4,
  ncol = 3,
  byrow = TRUE
)

datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

This cell is a duplicate of the previous one, demonstrating the conversion of split date components to a numeric matrix.

In [16]:
datematrix = matrix(
  as.numeric(unlist(datesplt)),
  nrow = 4,
  ncol = 3,
  byrow = TRUE
)

datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

This code uses `strsplit` to split a single word, 'Shalabh', into individual characters, resulting in a list where the first element is a vector of characters.

In [17]:
strsplit("Shalabh", split = "")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

This cell demonstrates the `nchar` function, which returns the number of characters in a string. It applies it to two different strings, `x` and `y`.

In [18]:
x = "R course 24.07.2022"
y = "Number of participants: 25"

nchar(x)

nchar(y)

[1] 19

[1] 26

This code uses the `nzchar` function, which checks if a character string has non-zero length. It returns `TRUE` for non-empty strings and `FALSE` for empty ones.

In [19]:
x = "R course 24.07.2022"
y = "Number of participants: 25"

nzchar(x)

nzchar(y)

[1] TRUE

[1] TRUE

This cell applies `nzchar` to a character vector `x` to determine which strings are non-empty.

In [20]:
x = c("Apple", "Banana", "Cake")

x

nzchar(x)

[1] "Apple"  "Banana" "Cake"

[1] TRUE TRUE TRUE

This code demonstrates `nzchar` on a character vector `y` that includes an empty string, showing how `FALSE` is returned for the empty string.

In [21]:
y = c("Apple", "", "Cake")

y

nzchar(y)

[1] "Apple" ""      "Cake"

[1]  TRUE FALSE  TRUE

This cell uses `nchar` to get the character length of each string in a character vector `x`.

In [22]:
x = c("Apple", "Banana", "Cake")

nchar(x)

[1] 5 6 4

This code applies `nchar` to a numeric vector `y`. R implicitly converts the numbers to character strings before calculating their length.

In [23]:
y = c(2, 4, 6)

nchar(y)

[1] 1 1 1

This cell demonstrates `nchar` on another numeric vector `z` with numbers of varying digit counts, illustrating how the character representation length is determined.

In [24]:
z = c(11, 222, 3333)

nchar(z)

[1] 2 3 4

This code shows `nchar` applied to a numeric vector `z1` containing decimal numbers. The decimal point itself contributes to the character count.

In [25]:
z1 = c(1.1, 2.22, 3.333)

nchar(z1)

[1] 3 4 5

This cell uses the `toupper` function to convert all characters in a given string `x` to uppercase.

In [26]:
x = "R course will start from 24.07.2022"

toupper(x)

[1] "R COURSE WILL START FROM 24.07.2022"

This code demonstrates the `tolower` function, which converts all characters in a given string `z` to lowercase.

In [27]:
z = "INDIAN INSTITUTE OF TECHNOLOGY"

tolower(z)

[1] "indian institute of technology"