<a href="https://colab.research.google.com/github/nikspatil0120/23102A0057_RProgramming/blob/main/R_Programmming_Week_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nikhil Patil

BE CMPN A 23102A0057

R Programmming Week 4

<h2>Changing the row and column Names

In [1]:
x = matrix(nrow=4, ncol=3, data=c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

Row name

In [4]:
rownames(x)=c("r1","r2","r3","r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

Column name

In [7]:
colnames(x)=c("c1","c2","c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

Assigning Specific Number to all the elements

In [8]:
x=matrix(nrow=4,ncol=2,data=2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

Diagonal Matrix with 1

In [10]:
d=diag(1,nrow=3 , ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

Daiagonal matrix with 5

In [11]:
d=diag(5,nrow=3,ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

<H2>Transponse of Matrix

In [12]:
x=matrix(nrow=4,ncol=2,data=1:8,byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [13]:
xt=t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

<H2>Rowwise and Columnwise sums

In [14]:
x=matrix(nrow=4,ncol=2,data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [16]:
rowSums(x)
colSums(x)

[1]  6  8 10 12

[1] 10 26

<h2>Rowwise and Columnwise Mean

In [18]:
x=matrix(nrow=4,ncol=2,data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [21]:
rowMeans(x)

[1] 3 4 5 6

In [22]:
colMeans(x)

[1] 2.5 6.5

<h2>Access to rows,columns or submatrices

In [24]:
x=matrix(nrow=5,ncol=3,byrow=T,data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

row

In [25]:
x[3,]

[1] 7 8 9

column

In [26]:
x[,2]

[1]  2  5  8 11 14

submatrix

In [27]:
x[4:5,2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

boundary element matrix

In [32]:
x[c(1,4),c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

<h2>Addition with Constant

In [34]:
x=matrix(nrow=4,ncol=2,byrow=T,data=1:8)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [35]:
x+5

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

<h2>Subtraction with Constant

In [36]:
x=matrix(nrow=4,ncol=2,byrow=T,data=1:8)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [37]:
x-5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

<h2>Multiplication with Constant

In [ ]:
x=matrix(nrow=4,ncol=2,byrow=T,data=1:8)
x

In [38]:
5*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

<h2>Division with Constant

In [39]:
x=matrix(nrow=4,ncol=2,byrow=T,data=1:8)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [40]:
x/2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

<h2>Matrix addition

In [41]:
x=matrix(nrow=4,ncol=2,byrow=T,data=1:8)
y=matrix(nrow=4,ncol=2,byrow=T,data=11:18)

In [43]:
x+y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

<h2>Matrix subtraction

In [44]:
x=matrix(nrow=4,ncol=2,byrow=T,data=1:8)
y=matrix(nrow=4,ncol=2,byrow=T,data=11:18)

In [45]:
x-y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

<h2>Various arithmetic operations

In [51]:
x=matrix(nrow=4,ncol=2,byrow=T,data=1:8)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [52]:
x+4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [54]:
4*x-x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

<h2>Matrix mulitplication

In [58]:
x=matrix(nrow=4,ncol=2,byrow=T,data=1:8)
y=matrix(nrow=2,ncol=4,byrow=T,data=11:18)

In [60]:
x%*%y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [61]:
y%*%x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [62]:
x=matrix(nrow=4,ncol=2,byrow=T,data=1:8)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [63]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [64]:
t(x)%*%x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [65]:
x%*%t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

In [66]:
x=matrix(nrow=4,ncol=2,byrow=T,data=1:8)

crossproduct of x , xx' using function

In [67]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

<h2>Concatenation of Matrix

In [68]:
x=matrix(nrow=4,ncol=2,byrow=T,data=1:8)
y=matrix(nrow=4,ncol=2,byrow=T,data=11:18)

Row

In [69]:
rbind(x,y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,]  7    8
[5,] 11   12
[6,] 13   14
[7,] 15   16
[8,] 17   18

Column

In [70]:
cbind(x,y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16
[4,] 7    8    17   18

In [71]:
y=matrix(nrow=2,ncol=2,byrow=T,data=c(84,100,100,120))
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

Calculate Inverse

In [72]:
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

Eigen Values and Eigen Vectors

In [73]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

<h2>Logical Operators

Logical OR

In [74]:
x=8
x<10 || x<2

[1] TRUE

Element wise Logical OR

In [80]:
x=c(8,18)
(x<10) | (x<2)

[1]  TRUE FALSE

Logical AND

In [81]:
x=5
x<10 && x>2

[1] TRUE

Element Wise Logical AND

In [82]:
x=c(8,18)
x<10 & x>2

[1]  TRUE FALSE

In [85]:
x=1:6
x>2 & x<5
x[x>2 & x<5]

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

In [86]:
x=5
Logical1=x>2
Logical1

[1] TRUE

is.logical check whether the expression is logical operation or not

In [87]:
is.logical(Logical1)

[1] TRUE

In [89]:
Logical2=x!=5
Logical2

[1] FALSE

In [90]:
is.logical(Logical2)

[1] TRUE

In [92]:
isTRUE(8<6)
isTRUE(8>6)
isFALSE(8<6)
isFALSE(8>6)

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE