<a href="https://colab.research.google.com/github/nikspatil0120/23102A0057_RProgramming/blob/main/R_Week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nikhil Surendra Patil

BE CMPN A 23102A0057

NA is assigned as missing data

In [1]:
x=NA

Check if it is a missing value

In [2]:
is.na(x)

[1] TRUE

In [3]:
x=c(11,NA,13,NA)

In [4]:
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

In [5]:
x=c(11,NA,13,NA)

Calculating mean of a vector having missing value

In [6]:
mean(x)

[1] NA

Calculating mean of a vector having missing value by removing the missing value

In [7]:
mean(x,na.rm=TRUE)

[1] 12

In [8]:
x=c(11,NA,13,NA)
x

[1] 11 NA 13 NA

which gives the index of the satisfied condition

In [9]:
which(is.na(x))

[1] 2 4

sum gives the number of elements satisfying the given condition

In [10]:
sum(is.na(x))

[1] 2

complete.cases() functtion identifies rows which are complete cases

In [11]:
complete.cases(x)

[1]  TRUE FALSE  TRUE FALSE

na.omit() returns the object with listwise deletion of missing values

In [13]:
y=na.omit(x)
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [17]:
mean(x)

[1] NA

In [18]:
mean(y)

[1] 12

<h2>Conditonal statements

if statement

In [20]:
x=5
if(x>4)x*3

[1] 15

In [21]:
x=3
if(x>4)x*3

If-else statement

In [25]:
x=5
if(x==3)
{
  x=x-1
}else{
  x=2*x
}
x

[1] 10

In [26]:
x=6
if(x>3)
{
  print("Value is more than 3")
}else{
  print("Value is less than 3")
}

[1] "Value is more than 3"

if-else ladder

In [27]:
x=5
if(x==3){
  x=x-1
}else if(x<3)
{
  x=x+5
}else{
  x=2*x
}
x

[1] 10

In [28]:
x=1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

ifelse() function takes conditon,then statemtn which is true and then false

In [29]:
ifelse(x<6,x^2,x+1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [30]:
x=c(7,8,9,4)
x

[1] 7 8 9 4

In [31]:
ifelse(x%%2==10,"even number","odd number")

[1] "odd number" "odd number" "odd number" "odd number"

switch() function

In [32]:
switch(2,"apple","banana","orange")

[1] "banana"

In [34]:
switch("color","color"="blue","gender"="male","volume"=50)

[1] "blue"

In [35]:
x=c(10,15,8,14,6,12)
x

[1] 10 15  8 14  6 12

which gives the index of the satisfied condition

In [36]:
which(x==14)

[1] 4

In [37]:
which(x!=12)

[1] 1 2 3 4 5

In [38]:
which(x>10)

[1] 2 4 6

In [39]:
x=matrix(nrow=3,ncol=3,data=1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [40]:
which.min(x)

[1] 1

In [41]:
which.max(x)

[1] 9

In [44]:
which(x%%2==1)

[1] 1 3 5 7 9

In [45]:
which(x%%2==1,arr.ind=TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3

In [51]:
x=c(1:9,6,4,NA,8)
mean(na.omit(x))

[1] 5.25