<a href="https://colab.research.google.com/github/nikspatil0120/23102A0057_RProgramming/blob/main/R_Week7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nikhil Surendra Patil

BE CMPN A 23102A0057

##Seequence

The `1:10` syntax in R creates a sequence of integers from 1 to 10 (inclusive).

In [1]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

This creates a decreasing sequence of integers from 10 to 1.

In [2]:
10:1

 [1] 10  9  8  7  6  5  4  3  2  1

This creates an increasing sequence of integers from 5 to 15.

In [3]:
5:15

 [1]  5  6  7  8  9 10 11 12 13 14 15

This creates a decreasing sequence of integers from 15 to 5.

In [4]:
15:5

 [1] 15 14 13 12 11 10  9  8  7  6  5

This creates a decreasing sequence of integers from -1 to -10.

In [5]:
-1:-10

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

This creates an increasing sequence of integers from -10 to 1.

In [6]:
-10:1

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1

This creates a decreasing sequence of integers from -5 to -15.

In [7]:
-5:-15

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

When using the colon operator with decimal numbers, R truncates them to integers. So, `1.23:10` is equivalent to `1:10`.

In [8]:
1.23:10

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

Similar to the previous example, R truncates the decimal numbers to integers, resulting in `1:10`.

In [9]:
1.23:10.54

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

This truncates to `10:2`, creating a decreasing sequence.

In [10]:
10.54:2.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

This truncates to `-1:-10`, creating a decreasing sequence.

In [11]:
-1.23:-10

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

This truncates to `-5:6`, creating an increasing sequence.

In [12]:
-5.23:6

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

The `seq()` function generates sequences. When given a single argument, like `seq(10)`, it generates a sequence from 1 to that number.

In [13]:
seq(10)

 [1]  1  2  3  4  5  6  7  8  9 10

This is equivalent to `seq(1:10)`, which simplifies to `seq(1,2,3,4,5,6,7,8,9,10)` effectively generating numbers from 1 to 10.

In [14]:
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

This code defines a variable `x` as 2. Then `seq(1, x, x/10)` creates a sequence starting at 1, ending at `x` (2), with increments of `x/10` (0.2).

In [15]:
x=2
seq(1,x,x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

Here, `x` is set to 50. The `seq(0, x, x/10)` function generates a sequence starting at 0, ending at 50, with increments of `x/10` (5).

In [16]:
x=50
seq(0,x,x/10)

 [1]  0  5 10 15 20 25 30 35 40 45 50

This code creates a sequence `x` from 1 to 50 with an increment of 0.5 (1/2), and then displays the sequence.

In [18]:
x=seq(1,50,1/2)
x

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

This cell multiplies each element of the `x` sequence (defined in the previous cell) by 2 and stores it in `y`, then displays `y`.

In [20]:
y=2*x
y

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

This code defines a numeric vector `x` and then creates an index vector `ind` using `seq(along=x)`. `seq(along=x)` generates a sequence of numbers from 1 to the length of `x`.

In [21]:
x=c(9,8,7,6)
ind=seq(along=x)
ind

[1] 1 2 3 4

This accesses the element of `x` at the index specified by the second element of `ind`.

In [22]:
x[ind[2]]

[1] 8

The `Sys.time()` function in R returns the current system date and time.

In [24]:
Sys.time()

[1] "2026-09-03 04:08:50 UTC"

The `Sys.Date()` function in R returns the current system date.

In [25]:
Sys.Date()

[1] "2026-09-03"

This uses `seq()` to generate a sequence of dates. It starts from January 1, 2010, ends at January 1, 2017, and generates dates with a step of 'years'.

In [26]:
seq(as.Date("2010-01-01"),as.Date("2017-01-01"),by="years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

This generates a sequence of 6 dates, starting from January 1, 2010, with each date incrementing by 'days'.

In [27]:
seq(as.Date("2010-01-01"),by="days",length=6)

[1] "2010-01-01" "2010-01-02" "2010-01-03" "2010-01-04" "2010-01-05"
[6] "2010-01-06"

This generates a sequence of 6 dates, starting from January 1, 2010, with each date incrementing by 'months'.

In [28]:
seq(as.Date("2010-01-01"),by="months",length=6)

[1] "2010-01-01" "2010-02-01" "2010-03-01" "2010-04-01" "2010-05-01"
[6] "2010-06-01"

This generates a sequence of 6 dates, starting from January 1, 2010, with each date incrementing by 'years'.

In [29]:
seq(as.Date("2010-01-01"),by="years",length=6)

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01"

This code defines a `startdate` and `enddate`. It then generates a sequence of dates from `enddate` back to `startdate`, decrementing by one month each time.

In [31]:
startdate=as.Date("2016-1-1")
enddate=as.Date("2017-1-1")
out=seq(enddate,startdate,by="-1 month")
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

The built-in `letters` constant in R provides a character vector of all lowercase letters of the English alphabet.

In [32]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

This extracts a slice of the `letters` vector, specifically elements from index 1 to 3 (i.e., 'a', 'b', 'c').

In [34]:
letters[1:3]

[1] "a" "b" "c"

This extracts elements from index 3 down to 1, resulting in 'c', 'b', 'a'.

In [35]:
letters[3:1]

[1] "c" "b" "a"

This extracts elements from index 21 to 23 of the `letters` vector.

In [36]:
letters[21:23]

[1] "u" "v" "w"

This extracts the element at index 2 from the `letters` vector.

In [37]:
letters[2]

[1] "b"

The built-in `LETTERS` constant in R provides a character vector of all uppercase letters of the English alphabet.

In [38]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

This extracts elements from index 1 to 3 of the `LETTERS` vector.

In [39]:
LETTERS[1:3]

[1] "A" "B" "C"

This extracts elements from index 21 to 23 of the `LETTERS` vector.

In [40]:
LETTERS[21:23]

[1] "U" "V" "W"

This extracts the element at index 2 from the `LETTERS` vector.

In [41]:
LETTERS[2]

[1] "B"

##Repeat

The `rep()` function in R is used for replicating elements of vectors. `rep(3.5, times=10)` replicates the number 3.5 ten times.

In [42]:
rep(3.5,times=10)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

This replicates the vector `1:4` (which is `c(1, 2, 3, 4)`) two times.

In [43]:
rep(1:4,2)

[1] 1 2 3 4 1 2 3 4

This defines a vector `x` as a sequence from 1 to 4 and then displays it.

In [44]:
x=1:4
x

[1] 1 2 3 4

This replicates the vector `x` (which is `c(1, 2, 3, 4)`) three times.

In [45]:
rep(x,times=3)

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

This replicates each element of vector `x` individually three times before moving to the next element.

In [46]:
rep(x,each=3)

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

This replicates each element of the sequence `1:4` two times.

In [47]:
rep(1:4,each=2)

[1] 1 1 2 2 3 3 4 4

This command combines `each` and `times`. It replicates each element of `1:4` two times, and then repeats this entire sequence three times.

In [49]:
rep(1:4,each=2,times=3)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

This command is similar to the previous one, but with `times` and `each` arguments swapped. It replicates the entire vector `1:4` three times, and then each element within that resulting sequence is replicated two times.

In [50]:
rep(1:4,times=3,each=2)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

This replicates each element of `1:4` a different number of times, as specified by the vector `2:5`. So, 1 is repeated 2 times, 2 is repeated 3 times, 3 is repeated 4 times, and 4 is repeated 5 times.

In [51]:
rep(1:4,2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

This defines a sequence `ans` starting from 2, ending at 8, with a step of 2, and then displays `ans`.

In [53]:
ans=seq(from=2,to=8,by=2)
ans

[1] 2 4 6 8

This replicates each element of `1:4` by the corresponding count in the `ans` vector. So, 1 is repeated 2 times, 2 is repeated 4 times, 3 is repeated 6 times, and 4 is repeated 8 times.

In [54]:
rep(1:4,ans)

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

This creates a 2x2 matrix `x` with elements 1 to 4, filled row by row (`byrow=T`), and then displays the matrix.

In [55]:
x=matrix(nrow=2,ncol=2,data=1:4,byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4

This replicates all elements of the matrix `x` three times, effectively flattening the matrix into a vector and then replicating its elements.

In [56]:
rep(x,3)

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

This replicates the character vector `c("a", "b", "c")` two times.

In [58]:
rep(c("a","b","c"),2)

[1] "a" "b" "c" "a" "b" "c"

This replicates the character vector `c("apple", "banana", "cake")` two times.

In [60]:
rep(c("apple","banana","cake"),2)

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

The `length.out` argument in `rep()` specifies the total length of the resulting vector. Here, it replicates the number 2 until the resulting vector has a length of 5.

In [61]:
rep(2,length.out=5)

[1] 2 2 2 2 2

The `length` argument is an alias for `length.out` and functions identically, replicating 2 five times.

In [62]:
rep(2,length=5)

[1] 2 2 2 2 2

This replicates the vector `c(2, 3)` until the resulting vector has a length of 5. It cycles through the elements (2, 3, 2, 3, 2).

In [63]:
rep(c(2,3),length=5)

[1] 2 3 2 3 2

This replicates the vector `c(2, 3, 4)` until the resulting vector has a length of 5. It cycles through the elements (2, 3, 4, 2, 3).

In [64]:
rep(c(2,3,4),length=5)

[1] 2 3 4 2 3

This replicates the string "apple" five times.

In [65]:
rep("apple",length=5)

[1] "apple" "apple" "apple" "apple" "apple"

This replicates the vector `c("a", "b", "c")` to a total length of 2, cycling through the elements.

In [68]:
rep(c("a","b","c"),length=2)

[1] "a" "b"

This replicates the vector `c("a", "b", "c")` to a total length of 5, cycling through the elements.

In [67]:
rep(c("a","b","c"),length=5)

[1] "a" "b" "c" "a" "b"

This defines a numeric vector `y` with values `(8, 5, 7, 6)` and then displays it.

In [69]:
y=c(8,5,7,6)
y

[1] 8 5 7 6

##Sorting

The `sort()` function sorts the elements of a vector in ascending order by default.

In [70]:
sort(y)

[1] 5 6 7 8

This sorts the elements of vector `y` in descending order due to `decreasing = TRUE`.

In [72]:
sort(y,decreasing =TRUE)

[1] 8 7 6 5

This redefines the numeric vector `y` with new values `(9, 8, 5, 7, 6)` and displays it.

In [74]:
y=c(9,8,5,7,6)
y

[1] 9 8 5 7 6

##Ordering

The `order()` function returns a permutation of indices that sorts the vector `y`. It does not return the sorted vector itself, but rather the positions where each sorted element originally was.

In [75]:
order(y)

[1] 3 5 4 2 1

This returns the indices that would sort vector `y` in descending order.

In [76]:
order(y,decreasing = TRUE)

[1] 1 2 4 5 3

##Mode

The `mode()` function in R returns the *storage mode* of an object, not the statistical mode (most frequent value). For a numeric value like `2.432`, its mode is "numeric".

In [77]:
mode(2.432)

[1] "numeric"

For a numeric vector, the `mode()` function returns "numeric".

In [78]:
mode(c(3,4,5,6,7,8))

[1] "numeric"

For a character string, the `mode()` function returns "character".

In [79]:
mode("India")

[1] "character"

For a character vector, the `mode()` function returns "character".

In [80]:
mode(c("India","CANADA"))

[1] "character"

For a factor object (categorical variable), the `mode()` function returns "numeric" because factors are internally stored as integer codes.

In [81]:
mode(factor(c("UP","MP")))

[1] "numeric"

For a list, the `mode()` function returns "list".

In [82]:
mode(list("INDIA","USA"))

[1] "list"

For a data frame, the `mode()` function returns "list" because a data frame is essentially a list of vectors of equal length.

In [86]:
mode(data.frame(x=1:2,y=c("India","USA")))

[1] "list"

For a function, the `mode()` function returns "function".

In [87]:
mode(print)

[1] "function"

##List

This code creates two 2x2 matrices, `x1` and `x2`, filled with values 1-4 and 5-8 respectively, filling by row.

In [88]:
x1=matrix(nrow=2,ncol=2,data=1:4,byrow=T)
x2=matrix(nrow=2,ncol=2,data=5:8,byrow=T)

This displays the content of matrix `x1`.

In [89]:
x1

     [,1] [,2]
[1,] 1    2
[2,] 3    4

This displays the content of matrix `x2`.

In [90]:
x2

     [,1] [,2]
[1,] 5    6
[2,] 7    8

This creates a list named `matlist` containing the two matrices `x1` and `x2`, and then displays the list.

In [92]:
matlist=list(x1,x2)
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

This uses single square brackets `[]` to access the first element of the list `matlist`. When using `[]` with a list, it returns a new list containing the selected elements, even if only one element is selected.

In [93]:
matlist[1]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

This creates a list `z1` containing three different types of objects: a character vector, a numeric vector (generated by `rep`), and a matrix. It then displays the list.

In [96]:
z1=list(c("water","juice","lemonade"),rep(1:4,each=2),matrix(data=5:8,nrow=2,ncol=2,byrow=T))
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

This uses double square brackets `[[]]` to extract the *content* of the first element of list `z1`. This extracts the actual character vector `c("water", "juice", "lemonade")`.

In [97]:
z1[[1]]

[1] "water"    "juice"    "lemonade"

This attempts to extract the second element from a sub-list created by `z1[1]`. `z1[1]` returns a list containing only the first element of `z1`. Trying to index this new list with `[2]` will result in `NULL` if there isn't a second element in the sub-list (which there isn't).

In [98]:
z1[1][2]

[[1]]
NULL

In [99]:
z1[[1]][2]

[1] "juice"